Week 3
dullzebra/react-chat pull request #2
Opened 2018-03-19 08:58 UTC by dullzebra

1. Реализованы методы createChat, leaveChat, deleteChat, editUser, sendMessage
2. Добавлены сокеты (soket.io) для получения новых новых сообщений и новых чатов
3. Улучшена работа  запросами к API: 
  предотвращение нового запроса, пока не завершился текущий такой же ( isFetching) ; 
  показ пользователю серверных ошибок при регистрации и при действиях  с чатом;
4. Блокировка элементов  интерфейса при отсутствии связи с сервером.

2018-03-20 03:24 UTC, TheDarkestDay commented
[Что хорошо]

[Что изменить]
1. Удалить закоменнтированные участки кода
2. Можно гораздо смелее использовать деструктуризацию (например, в редьюсерах для разбора action-ов)
3. Сейчас есть папка constants с типами action-ов, и есть одноименный файл в папке utils. Стоит переименовать файлы согласно их содержимому, чтобы не возникало путаницы.
4. Нужно вынести адрес сервера в отдельную константу (это замечание еще с прошлого ревью)
5. Возможны ситуации, когда возникает несколько подключений к серверу по WebSockets. Это приводит к тому, что мы можем, например, получить два одинаковых сообщения о том, что чат создан (по одному на каждое соединение). Такое поведение приводит к ошибкам. Необходимо обрабатывать такие ситуации: то есть, подключаться к сокету только если мы еще не подключены.

2018-03-20 03:35 UTC, TheDarkestDay requested changes
[Что хорошо]

1. Заявленные функции в целом работают (кроме случая, указанного в пункте 5 секции "Что изменить").

[Что изменить]

1. Удалить закоменнтированные участки кода
2. Можно гораздо смелее использовать деструктуризацию (например, в редьюсерах для разбора action-ов)
3. Сейчас есть папка constants с типами action-ов, и есть одноименный файл в папке utils. Стоит переименовать файлы согласно их содержимому, чтобы не возникало путаницы.
4. Нужно вынести адрес сервера в отдельную константу (это замечание еще с прошлого ревью)
5. Возможны ситуации, когда возникает несколько подключений к серверу по WebSockets. Это приводит к тому, что мы можем, например, получить два одинаковых сообщения о том, что чат создан (по одному на каждое соединение). Такое поведение приводит к ошибкам. Необходимо обрабатывать такие ситуации: то есть, подключаться к сокету только если мы еще не подключены.

2018-03-20 07:05 UTC, dullzebra commented
по п. 4 не соглашусь с настойчивой формулировкой **нужно**.   
**Можно** вынести в отдельную константу, а можно и не выносить в масштабах такого проекта.

2018-03-21 12:33 UTC, anstsot commented
[Что хорошо]

- Весь функционал реализован и работает
- Приятные цвета чата

[Что изменить]

- Очень напоминает оригинальный код ментора
- При Slow 3G делает в сайдбаре активным чат, который выбираешь последним, но сообщения подгружаются из чата, который был выбран первый

2018-03-23 19:54 UTC, denysdovhan reviewed
[Что хорошо]

* В целом, все работает и реализовано все.

[Что изменить]

* Вопросов нет.

2018-03-25 07:39 UTC, merged